### ISSUE TITLE
standard units for runtime

### ISSUE THREAD

**Issue by nickp60** [vdblab/vdblab-shotgun#35]
runtime should be [specified in minutes.](https://snakemake.readthedocs.io/en/stable/executing/cluster.html#advanced-resource-specifications)  Some of the rules are specifying in a "HH:MM" string.

**Comment by funnell** [comment]
@nickp60 I don't think we need to specify in minutes, our LSF profile just appends whatever we put there to the "-W" arg
https://github.com/vdblab/vdblab-profile/blob/9c7c5eeaf86cf50bc0f399be77694f57b4a629f5/lsf_submit.py#L103

**Comment by funnell** [comment]
we can still switch if you still prefer setting minutes though

**Comment by nickp60** [comment]
The docs linked above and [here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#standard-resources) specify that runtime should be specified in minutes or as a time interval with units.  Bare unitless HH:MM worked for us on lsf but we should probably try to make it portable.  If we do the interval and units, it says they translate it to minutes anyway with the human readable package. The LSF accepts minutes as well:
>the run limit is in the form of [hour:]minute. The minutes can be specified as a number greater than 59. For example, three and a half hours can either be specified as 3:30, or 210.

**Comment by nickp60** [comment]
Well this was timely (pun intended).  With snakemakes latest release [7.20](https://github.com/snakemake/snakemake/compare/v7.19.1...v7.20.0) the old syntax raises errors.
```
cat /data/brinkvd/isabl/data_lake/analyses/19/92/1992/hea│d_job.err                                                                                                  
Building DAG of jobs...                                                                                    
WorkflowError:                                                                                             
Cannot parse runtime value into minutes for setting runtime resource: 48:00
``

**Comment by funnell** [comment]
nice! you preemptively fixed a bug 👍
