### ISSUE TITLE
preprocess: parallelize `get_all_host_reads` rule

### ISSUE THREAD

**Issue by funnell** [vdblab/vdblab-shotgun#42]
Since the `get_all_host_reads` rule in preprocess.smk can be a somewhat long running rule, we could try splitting it up like this:
1. Run the `samtools view` and `bamToFastq` commands as a rule that is parallelized over input bams, rather than with the `for` loop
2. Run the `cat ... | pigz ...` step as a downstream rule that is parallelized over R1,R2

**Comment by nickp60** [comment]
Thanks for finding this!  resolved
