### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas' Error in rule preprocess_merge_logs_for_multiqc:

### ISSUE THREAD

**Issue by funnell** [vdblab/vdblab-shotgun#48]
the `merge_logs_for_multiqc` preprocess rule specifies a conda env but not a container, and so when run without `--use-conda` will produce a ModuleNotFoundError

**Comment by nickp60** [comment]
I've only used snakemake from conda/mamba installs which [includes pandas](https://bioconda.github.io/recipes/snakemake/README.html).  Feel free to add a note to the readme to clarify though, or add a pandas docker image; up to you.

**Comment by funnell** [comment]
I think I have just `snakemake-minimal` installed which doesn't come with all the bells and whistles. I'll probably go with the docker image route.

**Comment by nickp60** [comment]
resolved with bd4c83c40
