### ISSUE TITLE
test.sh issues

### ISSUE THREAD

**Issue by funnell** [vdblab/vdblab-shotgun#66]
* `--profile ${SNAKEPROFILE}` used but redundant now that `SNAKEMAKE_PROFILE` is a mandatory env var
* hard-coded path: `/data/brinkvd/watersn/minikraken2_v2_8GB_201904_UPDATE` which doesn't exist anymore either
* test data missing from `.test` e.g. `SRR21986403`

**Comment by nickp60** [comment]
ff44f65
